### ISSUE TITLE
Add headers to show the current usage of the throttle limits

### ISSUE THREAD

**Issue by nkostadinov** [nestjs/throttler#1032]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The problem is that the client doesnt know if the endpoint enforces limits and what those limits are.

### Describe the solution you'd like

Optionally add helper headers to help the consumer to know how much of the limit he has used so far. I've used other frameworks which expose these headers in the response:

X-Rate-Limit-Limit, the maximum number of requests allowed with a time period
X-Rate-Limit-Remaining, the number of remaining requests in the current time period
X-Rate-Limit-Reset, the number of seconds to wait in order to get the maximum number of allowed requests

### What is the motivation / use case for changing the behavior?

These will allow clients to know the limits and act accordingly or display something to the users.

**Comment by jmcdo29** [comment]
[We currently set these](https://github.com/nestjs/throttler/blob/master/src/throttler.guard.ts#L86). Are you seeing something different?
