### ISSUE TITLE
Throttler doesn't work in GraphQL but work in controller

### ISSUE THREAD

**Issue by mpx2m** [nestjs/throttler#1136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I read document and set up the global guard Throttler for restful controller and graphql resolver .

I use `autocannon` to test the function of Throttler.

### Minimum reproduction code

https://github.com/mpx2m/nest-rate-limiting-example

### Steps to reproduce

In `Minimum reproduction code`

***To test controller***

after run :
```bash
npm run test:controller-test 
```
return
```
statusCodeStats: { '200': { count: 10 }, '429': { count: 24836 } }
```

429 is returned and Throttler works well

***To test graphql***

```bash
npm run test:graphql-resolver-test
```

return
```
statusCodeStats: { '200': { count: 9727 } }
```

No 429 is returned

### Expected behavior

expect
```bash
npm run test:graphql-resolver-test
```
statusCodeStats contains 429 result

### Package version

3.0.0

### NestJS version

9.0.1

### Node.js version

v16.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Seems like something in the way `autocannon` is sending the request, the req ip gets lost for the graphql example. If you use a CLI tool like `curl` or `xh` you get the proper `429` response after 10 request 
```sh
for i in {0..10}; do
curl http://localhost:3000/graphql -H 'content-type: application/json' -H 'accept: application/
json, */*;q=0.5' -d '{"query":"query test { test }"}'
done
{"data":{"test":"test"}}
{"data":{"test":"test"}}
{"data":{"test":"test"}}
{"data":{"test":"test"}}
{"data":{"test":"test"}}
{"data":{"test":"test"}}
{"data":{"test":"test"}}
{"data":{"test":"test"}}
{"data":{"test":"test"}}
{"data":{"test":"test"}}
{"errors":[{"message":"ThrottlerException: Too Many Requests","locations":[{"line":1,"column":14}],"path":["test"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"response":"ThrottlerException: Too Many Requests","status":429,"message":"ThrottlerException: Too Many Requests","name":"ThrottlerException"}}}],"data":null}
```

**Comment by mpx2m** [comment]
thank you!

**Comment by jmcdo29** [comment]
Oh! You know what it is? GQL **always** returns a 200, so this error is being return in the `errors` array of the data, even though the HTTP 429 is properly thrown. The ip actually is there and properly being recorded (as `::1` or IPv6 localhost), but because GQL will always try to return a 200, it _looks_ like it's not being thrown (though the simple shell script above does in fact confirm that it is)

**Comment by mpx2m** [comment]
yes, I truly forgot that!
