### ISSUE TITLE
Make the `storage` field in the `ThrottlerStorage` interface optional

### ISSUE THREAD

**Issue by MitchellCash** [nestjs/throttler#1221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently the `storage` field in the `ThrottlerStorage` interface is required:

https://github.com/nestjs/throttler/blob/92cd4ebf507b3bed4efbaeb7bb47bd1738a62dc3/src/throttler-storage.interface.ts#L1-L8

This makes sense for the in memory cache, but I have built my own Redis storage service which implements the `ThrottlerStorage` interface and I have no use for the `storage` field from what I can tell.

It would be nice if this field was deemed optional so I don't have unused code sitting in my `ThrottlerRedisStorageService` which implements `ThrottlerStorage`.

I am happy to make a PR for this fix, but I just wanted to confirm this field is indeed optional when using your own storage option.

### Minimum reproduction code

See 'Steps to reproduce'.

### Steps to reproduce

```ts
import { Injectable } from '@nestjs/common';
import { ThrottlerStorage } from '@nestjs/throttler';

@Injectable()
export class ThrottlerRedisStorageService implements ThrottlerStorage {
  // storage: Record<string, number[]>; // <-- Throws a TypeScript error when not visible.

  addRecord(key: string, ttl: number): Promise<void> {
    return Promise.resolve(undefined);
  }

  getRecord(key: string): Promise<number[]> {
    return Promise.resolve([]);
  }
}
```

### Expected behavior

As far as I know, I do not require the `storage` field, so would prefer it to be optional to save an unused line of code.

### Package version

3.1.0

### NestJS version

9.1.4

### Node.js version

16.18.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Sounds like a good idea. We can probably actually just remove it from the interface, all that the guard needs to know is how to get a record and add a record

**Comment by jmcdo29** [comment]
Added to 5.0.0 in #1565
