### ISSUE TITLE
Is throttler limits number of request per user or on total count

### ISSUE THREAD

**Issue by nitinmagdumvista** [nestjs/throttler#1250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Is throttler limits number of request per user or on total count

example - if i configure throttler for 60 sec to allow only 10 request so it will be 10 request per user or total 10 request combining multiple users

because to avoid DDOS attack i want to set limit per user not on total request by multiple users

### Minimum reproduction code

https://github.com/nestjs/throttler/issues/new?assignees=&labels=needs+triage%2Cbug&template=Bug_report.yml

### Expected behavior

Is throttler limits number of request per user or on total count

### Package version

8.0.0

### NestJS version

8.0.0

### Node.js version

14.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Other

Is throttler limits number of request per user or on total count

**Comment by micalevisk** [comment]
by default, it is per IP:

https://github.com/nestjs/throttler/blob/519199c68696092d9ffcf08230e9ca187c826799/src/throttler.guard.ts#L99-L101

**Comment by jmcdo29** [comment]
This module works by tracking a combination of IP and URL for its key tracking. That means if you set a TTL of 60 and a limit of 10, each user can hit an endpoint up to 10 times in a 60 second time frame. If they exceed that, they can still hit other endpoints.

**Comment by nitinmagdumvista** [comment]
@jmcdo29 @micalevisk Thanks a lot

**Comment by nitinmagdumvista** [comment]
what is the standard configuration for an public facing application 60 and10
or it varies  as per application and load

**Comment by jmcdo29** [comment]
It varies. 
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
