### ISSUE TITLE
Add a way to use Throttler multiple times

### ISSUE THREAD

**Issue by quazariun** [nestjs/throttler#1369]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The problem is I can't use two **Throttler** decorators.

### Describe the solution you'd like

I want to make something like:
```javascript
    @UseGuards(ThrottlerGuard)
    @Throttle(10,60)
    @Throttle(1000, 86400)
    @Post("/teste")
```

With this, is possible to make a business rule:
   - Ten request per minute
   - One thousand request per day

### Teachability, documentation, adoption, migration strategy

![image](https://user-images.githubusercontent.com/26460729/220778268-a3ecffa3-73f9-494d-87aa-f15684a5e5ac.png)

It's a pretty good way to use this library.

### What is the motivation / use case for changing the behavior?

It's the necessity to **Rate Limiting** on micro-time (seconds) and macro-time (days).

**Comment by jmcdo29** [comment]
I think this could be manageable with a new API and mixin guard. Essentially something like `ThrottlerGuard('macro')` where `macro` is essentially just a label. That same label would then be added to the `@Throttle()` decorator as we overhaul that to be `@Throttle({ ttl, limit, label? })` and the guard implementation itself uses the reflector plus the label (if it exists) to get specific metadata based on label + metadata key for that labeled guard. This way, it could be used multiple times over for multiple rate limits that need to be adhered to.
