### ISSUE TITLE
Using throttler with graphql causes: `TypeError: Cannot read properties of undefined (reading 'header')`

### ISSUE THREAD

**Issue by sadams** [nestjs/throttler#1437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Following the readme in this repo, the above PR has included the code that should make it compatible with gql:
```typescript
@Injectable()
export class GqlThrottlerGuard extends ThrottlerGuard {
  getRequestResponse(context: ExecutionContext) {
    const gqlCtx = GqlExecutionContext.create(context);
    const ctx = gqlCtx.getContext();
    return { req: ctx.req, res: ctx.res }; // ctx.request and ctx.reply for fastify
  }
}
```
however, it throws this error: 
```
[Nest] 95109  - 31/03/2023, 09:21:31   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'header')
TypeError: Cannot read properties of undefined (reading 'header')
    at GqlThrottlerGuard.handleRequest (/[...]/nest/sample/23-graphql-code-first/node_modules/@nestjs/throttler/src/throttler.guard.ts:88:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
My best guess is this is caused by a recent upgrade to `@nestjs/graphql` to make it compatible with a more recent version of apollo.
An example based on a the samples in the (forked) nestjs core repo can be found here: https://github.com/sadams/nest/pull/1

### Minimum reproduction code

https://github.com/sadams/nest/pull/1

### Steps to reproduce

1. clone branch from here: https://github.com/sadams/nest/pull/1
2. run `npm install`
3. run `npm start` in `sample/23-graphql-code-first` directory
4. visit http://localhost:3000/graphql
5. execute `query {recipes{title}}`
6. see output in terminal

### Expected behavior

The request should go through normally until they are throttled, at which point the normal throttler behaviour should kick in.

### Package version

4.0.0

### NestJS version

9.3.12

### Node.js version

v16.19.0

### In which operating systems have you tested?

- [X] macOS

**Comment by jmcdo29** [comment]
More than likely, `res` isn't being forwarded to the context by default and you'll need to add it by adding this to the gql options: `context: ({ req, res }) => ({ req, res })`

**Comment by sadams** [comment]
Thanks @jmcdo29 for your response. I added the context, and as you said, it worked.

However, my actual use case was using fastify, and when i updated the example it failed again.

To be fair, it's in the README.md (i just missed it):

>You must use `Express` and `apollo-server-express` as your GraphQL server engine. This is
  the default for Nest, but the [`apollo-server-fastify`](https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-fastify) package does not currently support passing `res` to the `context`, meaning headers cannot be properly set.

What's interesting is it worked before we upgraded nest (and after the above was added to the README), so it seems the above was incorrect at one point, but is now correct.

Either way, I think it makes sense to update the README to remove an indication that you can use fastify with nestjs-graphql and nestjs-throttler. E.g. `// ctx.request and ctx.reply for fastify` in:
```
@Injectable()
export class GqlThrottlerGuard extends ThrottlerGuard {
  getRequestResponse(context: ExecutionContext) {
    const gqlCtx = GqlExecutionContext.create(context);
    const ctx = gqlCtx.getContext();
    return { req: ctx.req, res: ctx.res }; // ctx.request and ctx.reply for fastify
  }
}
```
I can put a PR up.
Thanks again.

**Comment by sadams** [comment]
FWIW i have reported an issue with nestjs-graphql here: https://github.com/nestjs/graphql/issues/2759

**Comment by mit4dev** [comment]
> More than likely, `res` isn't being forwarded to the context by default and you'll need to add it by adding this to the gql options: `context: ({ req, res }) => ({ req, res })`

Thank you so much, that worked for me. 🚀 

Specs:
Using Express

```
@nestjs/throttler: v4.2.1
@nestjs/core: 9.4.3
@nestjs/apollo: 12.0.9
@nestjs/graphql: 12.0.9
```
