### ISSUE TITLE
Context-based `ttl` and `limit` options

### ISSUE THREAD

**Issue by benjlevesque** [nestjs/throttler#1483]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The current `limit` and `ttl` options are statically configured, which prevents adjusting limits for specific users or IPs.

The existing `skipIf` is a workaround but isn't sufficient as it completely disables the throttling.  

### Describe the solution you'd like

Enable configuring the `limit` and `ttl` with a callback, like this: 

```ts
ThrottlerModule.forRoot({
      limit: () => 5,
      ttl: () => 60,
 }),
```

or
```ts
ThrottlerModule.forRoot({
      limit: async (context) => // ... retrieve something,
      ttl: async (context) => 60,
}),
```

and, for the decorator:

```ts
@Throttle(()=> 2, ()=> 10)
```

NB: for my current use case, the `ttl` is not mandatory; neither is the fact that these callbacks return Promises, but it seems reasonable. 

### What is the motivation / use case for changing the behavior?

Per-user / per-application rate limiting: normal users have a specific rate, and automations (machine to machine integrations) have a different rate.

**Comment by jmcdo29** [comment]
I think I'll take the work from #1484 (thanks for that) and merge it into a branch I'll be working on for the next major update as we'll then allow for multiple time spans as well, so just making all the breaking changes at once.

**Comment by benjlevesque** [comment]
hey @jmcdo29. OK that's great. What breaking change are you referring to? The change in #1484 doesn't break the API I think?

**Comment by jmcdo29** [comment]
Somehow I missed that you made that to where the functional approach works _with_ the static one. Nevermind on me saying it's a breaking change

**Comment by siisee11** [comment]
When will be the next major update?

**Comment by siisee11** [comment]
@benjlevesque 
I tried to use skipIf like below. But It is now allowed to use await in skipIf. Can you share what you do to solve this problem?
```
async skipIf(context) {
  // TODO: if user is premium user, skip throttling
  const request = context.switchToHttp().getRequest();
  const extractor = ExtractJwt.fromAuthHeaderAsBearerToken();
  const accessToken = ExtractJwt.fromExtractors([extractor])(request);
  console.log("THROTTLE:", accessToken);
  const payload = jwtService.decode(accessToken);
  const userId = payload.sub;
  const user = await usersService.findOne(userId);
  console.log("THROTTLE:", user);
  return false;
},
        ```

**Comment by alhajee** [comment]
**You don't want a database operation happening on your throttler guard**, as it's going to introduce unnecessary bottleneck.

What you can do is, read whatever user information you want from your **Cache** _(you can use Redis for this)_
