### ISSUE TITLE
this library does not support Nestjs 10.0.0

### ISSUE THREAD

**Issue by xuegao-tzx** [nestjs/throttler#1516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

this library does not support Nestjs 10.0.0

### Minimum reproduction code

this library does not support Nestjs 10.0.0

### Expected behavior

this library does not support Nestjs 10.0.0

### Package version

4.0.0

### NestJS version

10.0.0

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

### Other

this library does not support Nestjs 10.0.0

**Comment by jmcdo29** [comment]
Nest 10 literally released last night. I'm working on having this ready, have some patience as the team is spread across timezones

**Comment by jmcdo29** [comment]
`@nestjs/throttler@4.1.0` and greater support NestJS v10 (there are no breaking changes for this release, so it was just an update to the `peerDependencies`)

**Comment by Tukajo** [comment]
> Nest 10 literally released last night. I'm working on having this ready, have some patience as the team is spread across timezones

Jmcdo29, you DARE to have dinner and downtime? There's work to do!!

/sarcasm
