### ISSUE TITLE
4.2.0 is a BREAKING CHANGE for custom guards

### ISSUE THREAD

**Issue by kurt-west** [nestjs/throttler#1566]
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

PR #1484

### Versions

4.1.0 => 4.2.0

### Describe the regression

When extending the ThrottleGuard canActivate method or injecting the ThrottleModuleOptions into a custom guard with `@Inject(getOptionsToken())` limit and ttl are now type `Resolvable<number>` whereas previously they were type `number`.

### Minimum reproduction code

```ts

```

### Expected behavior

Expect when a public interface is updated to no longer be backwards compatible there would be a major release bump.

**Comment by jmcdo29** [comment]
Ah, yeah, I was thinking mainly about module configurations, not necessarily custom guards, but this would break those, wouldn't it? I'll revert the change and make it a part of 5.0.0. Thanks for reporting

**Comment by kurt-west** [comment]
Thank you. 

One nice, but not needed update for 5.0 would be to break out the `resolveValue()` method that currently lives in the guard to a separate file and publicly expose it - maybe `getResolvableValue()`. This would allow easy migration, simplified development of custom guards, and offer some protection against breaking changes in the unlikely that the implementation of `resolveValue()` needs to change.
