### ISSUE TITLE
Revert ttl when request failed

### ISSUE THREAD

**Issue by siisee11** [nestjs/throttler#1579]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I set throttle 1 request per minute. I don't want to make user wait for failed requests.

### Describe the solution you'd like

Revert expirationTime when request failed (Exception occur)

### What is the motivation / use case for changing the behavior?

apply throttle only for succeed requests.

**Comment by jmcdo29** [comment]
What are the conditions for a request failing? If a request makes it all the way through an endpoint, but fails at the last step, is that a failed request? Part of rate limiting is to manage the number of interactions the server is handling at a given time, and to ensure that it can keep up. If these are slow or long running database interactions, it may not make sense to reset the number of interactions even on a failure, as they could be very resource intensive.

**Comment by CzarOfScripts** [comment]
I would like to bring this up, I have a situation where I would like to restrict access to a router for a while after a successful request. In my case it's a request that would send a text message to register/reset password, but if there is any error (e.g. wrong data) then the request will be blocked, but that's not quite right.

If you have any idea how I could implement it, that would be cool.
