### ISSUE TITLE
No way to create custom key generator for storage

### ISSUE THREAD

**Issue by VladStepanov** [nestjs/throttler#1662]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I just want to have a opportunity to generate my own key. Md5 hash is good, but in real life there may be situations then you should connect to your redis and check `keys rl-*`.
I can't believe that such a popular lib doesn't have such a simple thing.

### Describe the solution you'd like

Global default customKey function
```js
.forRoot({
  customKey (context) {}
})
```

Local customKey function
```js
class ThrottlerFoo extends ThrottlerGuard {
  customKey (context) {}
}
```
Local function overrides global

### What is the motivation / use case for changing the behavior?

In real life there may be situations then you should connect to your redis and check/drop constraints

**Comment by jmcdo29** [comment]
You can extend the `ThrottlerGuard` and override the [`generateKey` method](https://github.com/nestjs/throttler/blob/master/src/throttler.guard.ts#L113)

**Comment by yudikubota** [comment]
I think this should be highlighted in the documentation.

**Comment by micalevisk** [comment]
@yudikubota feel free to open a PR to change that at https://github.com/nestjs/docs.nestjs.com
