### ISSUE TITLE
`this` is undefined in custom guard extending the ThrottlerGuard when overriding `generateKey` method

### ISSUE THREAD

**Issue by AljazOblonsek** [nestjs/throttler#1808]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

https://github.com/nestjs/throttler/commit/f5b9cc95c13fa48c07f74d18ea8ecbb40c20665f#diff-adac4b5893ae69db6dac7b5a6d1d0fa0131b1caf87291697bd13b23e3e00c41bR62

### Versions

5.0.1 -> 5.1.0

### Describe the regression

I have a custom ThrottleGuard that extends the base ThrottlerGuard. Within this custom guard, the `generateKey` method is overridden, and it invokes a private method named `myCustomMethod`, like so: `this.myCustomMethod()`. However, since version 5.1.0, it appears that `this` is undefined within the overridden `generateKey` method. Consequently, calling `this.myCustomMethod()` results in `undefined.myCustomMethod()`, leading to an undefined exception.

### Minimum reproduction code

Here is the full repository with reproduction steps included in the readme: https://github.com/AljazOblonsek/nestjs-throttler-this-undefined-issue

### Expected behavior

 `this` should be defined in the `generateKey` method

### Other

I believe the root cause lies in this section: https://github.com/nestjs/throttler/commit/f5b9cc95c13fa48c07f74d18ea8ecbb40c20665f#diff-adac4b5893ae69db6dac7b5a6d1d0fa0131b1caf87291697bd13b23e3e00c41bR63 Upon testing locally, I found that modifying `generateKey: this.options.generateKey || this.generateKey` to `generateKey: this.options.generateKey || this.generateKey.bind(this)` resolves the issue, restoring the normal functionality of the custom throttler guard. I'm willing to create a pull request to address this.

**Comment by micalevisk** [comment]
Please go ahead and create the PR

**Comment by AljazOblonsek** [comment]
> Please go ahead and create the PR

Opened the PR here 😊 https://github.com/nestjs/throttler/pull/1809
