### ISSUE TITLE
update README to reflect changes in WsThrottlerGuard

### ISSUE THREAD

**Issue by TrejGun** [nestjs/throttler#2047]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

<img width="1593" alt="image" src="https://github.com/user-attachments/assets/313c4b23-0b15-42e7-a3ac-b4f4a6d20acb">

### Describe the solution you'd like

updated docs

### What is the motivation / use case for changing the behavior?

we want to update our codebase to use latest version

**Comment by TrejGun** [comment]
up

**Comment by jmcdo29** [comment]
#2085
