### ISSUE TITLE
Version 6.0.0 is not working very well

### ISSUE THREAD

**Issue by tinhobe159** [nestjs/throttler#2054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![Screenshot 2024-07-21 at 19 03 14](https://github.com/user-attachments/assets/698442bc-72eb-4ae1-a979-d495783bfb99)
I call more than 10 times but it does not throw Error: To many requests. Does any one know why?

### Minimum reproduction code

https://github.com/tinhobe159/nestjs-learning

### Expected behavior

Expecting error to many requests

### Package version

6.0.0

### NestJS version

10.0.0

### Node.js version

18.20.4

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by samkiwi2019** [comment]
same issue here.  only works when included in the child module with the following code:

```
// xxx.module.ts
imports: [
    ThrottlerModule.forRoot([{
      ttl: 60000,
      limit: 10,
    }]),
  ],
providers: [
    {
      provide: APP_GUARD,
      useClass: ThrottlerGuard,
    },
  ],

// xxx.controller.ts
@Controller()
export class XXXController {
  constructor() {}

  @Throttle({ default: { limit: 3, ttl: seconds(60) } })
  @Get('/xxx/xxx/test')
  async test() {
    return 'test'
  }
```
Tried various other ways of importing it, but none worked. Version 5.2.0 has no issues at all.

**Comment by jmcdo29** [comment]
@tinhobe159 I'm able to make this work either by rapid firing requests from the terminal (for loops work well for this), or by using `seconds(60)` (where `seconds` is from `@nestjs/throttler`). Otherwise, the `ttl` is 60ms, which will be pretty hard as a human to hit

**Comment by BennoDev** [comment]
Same behaviour here. Doesn't work anymore, downgrading to 5.2.0 and it works again. 

Headers are set correctly but requests are still passing through.

```ts
@Module({
    imports: [
        ConfigModule.forRoot(configOptions),
        ThrottlerModule.forRootAsync({
            imports: [ConfigModule.forFeature(apiConfig)],
            inject: [apiConfig.KEY],
            useFactory: (config: ApiConfig) => ({
                storage: new ThrottlerStorageRedisService(
                    getRedisClient(config),
                ),
                throttlers: [
                    {
                        name: 'per-minute',
                        ttl: minutesToMilliseconds(1),
                        limit: config.api.rateLimit,
                    },
                ],
            }),
        }),
        LoggerModule,
        HealthModule,
        AuthModule,
    ],
    providers: [
        {
            provide: APP_GUARD,
            useClass: ThrottlerGuard,
        },
    ],
})
export class ApiModule {}
```
#### Headers: 
<img width="253" alt="image" src="https://github.com/user-attachments/assets/88ab9674-7f15-4b08-88cd-5c3e31a8460e">

#### Response still coming through (health check endpoint):
<img width="168" alt="image" src="https://github.com/user-attachments/assets/eea8cfb3-9a32-4301-ad18-64b1018eb1f0">

**Comment by jmcdo29** [comment]
@BennoDev Does it work if you use the memory store instead of Redis? Version 6.0.0 was _technically_ breaking at the library level, so if it hasn't been updated yet then there's a chance that it isn't returning what's expected by the main module.

**Comment by tinhobe159** [comment]
> @tinhobe159 I'm able to make this work either by rapid firing requests from the terminal (for loops work well for this), or by using `seconds(60)` (where `seconds` is from `@nestjs/throttler`). Otherwise, the `ttl` is 60ms, which will be pretty hard as a human to hit

Thank a lot. I change ttl from 60 to 6000 and it works.

**Comment by BennoDev** [comment]
> @BennoDev Does it work if you use the memory store instead of Redis? Version 6.0.0 was _technically_ breaking at the library level, so if it hasn't been updated yet then there's a chance that it isn't returning what's expected by the main module.

There's indeed a new version of the redis storage now. I'll check that one and see if the issue has been fixed.
