### ISSUE TITLE
Consider making Redis the default storage. Memory storage should be discouraged.

### ISSUE THREAD

**Issue by andrew-sol** [nestjs/throttler#2081]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

If an app is placed behind a load balancer (and many/most production apps are), there are many containers of the same app and each user request is often forwarded to a different app container. Different containers hold different data about user requests in memory, which makes the library useless in some cases (if you want to limit a route to 1 request per minute for example).

### Describe the solution you'd like

1. Consider making Redis the default storage.
2. The issue I described should be mentioned in the Proxies section of the readme doc.
3. It would be better if the Redis storage implementation was included in this repository and maintained by the library's developers.

### What is the motivation / use case for changing the behavior?

-

**Comment by micalevisk** [comment]
I like Redis but there are a bunch of others similar storage that we could use. Which is why I don't think that this package should define the storage. The in-memory one is the most accessible

**Comment by andrew-sol** [comment]
Redis is generally the best for most cases. Another option might be Memcached (but who is using it nowadays?). Most of the other options (including Mongo) have no sense for high-load applications or are not popular/accessible enough for recommendation.

**Comment by jmcdo29** [comment]
Forcing the use of Redis as the default storage could bring overhead to applications that normally wouldn't be using Redis in the first place. Of course, when the application starts scaling that will be a necessity, but for prototyping and showing that it works, or MVPs, it could create a large overhead that wouldn't be necessary or achievable. Letting it stay as an _option_ gives flexibility to the library, and while we can encourage the use of it, it shouldn't be the standard of just the library itself

**Comment by andrew-sol** [comment]
I'm not insisting on that. But at least you should update your docs to explain **when** the use of Redis is necessary.
Also, it would be nice if the doc included at least one example of the guard usage:
```ts
@UseGuards(ThrottlerGuard)
```

IMO the `@Throttle()` decorator could have applied the guard under the hood. And accept a guard constructor as the first param (optionally, if a non-standard guard is used).
