### ISSUE TITLE
Lost  export

### ISSUE THREAD

**Issue by TrejGun** [nestjs/throttler#2087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

ThrottlerRequest used in readme.md for WsThrottlerGuard is not exported from src/index

### Minimum reproduction code

https://github.com/nestjs/throttler/blob/master/README.md

### Expected behavior

interface is exported

### Package version

6.1.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I guess it's just a missing `export * from './throttler.guard.interface.ts';` at `src/index.ts`

**Comment by TrejGun** [comment]
yeah , I created a PR https://github.com/nestjs/throttler/pull/2088
