### ISSUE TITLE
missing package-lock.json?

### ISSUE THREAD

**Issue by Tony133** [nestjs/throttler#297]
Hi, I wanted to ask you would not miss the package-lock.json?

a curiosity / question

I hope you don't steal a lot of time :-)

**Comment by jmcdo29** [comment]
The package was built with `yarn` so there is a `yarn.lock` instead. @kamilmysliwiec do you have a strong preference of `yarn` vs `npm` when it comes to packages? I know most of the NestJS packages have a `package-lock` so if we need we can swap over to that before the first publish under the new name.

**Comment by Tony133** [comment]
Thanks for the reply @jmcdo29  :-)

**Comment by Tony133** [comment]
Also note that the package-lock.json is not specified in the .gitignore file if you decide to exclude it, at the moment.

So if you were to do a pull or more pulls and one forgets to exclude it if he always brings it back in commits from ago.

**Comment by jmcdo29** [comment]
Why would you want to exclude a lock file? Just so you don't have multiple locks in the same repo? I feel that's what Pull Request Reviews are for.

**Comment by Tony133** [comment]
Maybe I didn't make myself understood, sorry.

I just wanted to say that if one pulls right now as there is no package-lock in the repo, json adds the first person to pull.

In my opinion, perhaps it is better to put it as in all the packages of the NestJS organization.

I hope I am made to understand

**Comment by kamilmysliwiec** [comment]
@jmcdo29 i'm fine with either one (package-lock.json/yarn.lock). Whatever is easier for you :)
