### ISSUE TITLE
Proposal: use @commitlint/config-angular

### ISSUE THREAD

**Issue by Tony133** [nestjs/throttler#298]
I noticed that the other packages used this:  @commitlint/config-angular in place @commitlint/config-conventional

if you want can I do a pull?

**Comment by jmcdo29** [comment]
That's fine by me if you'd like to swap them out. Probably copy the `.commitlintrc.json` from one of the other repos to make sure we're staying aligned across projects.

**Comment by Tony133** [comment]
@jmcdo29  this and the pull #305
