### ISSUE TITLE
Add package installation method in README

### ISSUE THREAD

**Issue by Tony133** [nestjs/throttler#300]
It installs so right?

```
$ yarn add nestjs/throttler
```

if you want can I do a pull?

**Comment by jmcdo29** [comment]
We are working on the docs. This was a community package being brought in to the Nest organization. Once the docs are ready, the package will be published. Until then, the community version is still available at `nestjs-throttler`

**Comment by johannesschobel** [comment]
Dear @jmcdo29 , sorry for posting to this already closed issue.
Do you have an estimated timeframe for the new release? Does the API of this package change?

Thanks for commenting and putting your work into this library! :+1: 

All the best

**Comment by jmcdo29** [comment]
Hey @johannesschobel, Kamil and I are coordinating a release timeline. Once we're happy with the docs, I'll trigger the release under the new name. Until then, `nestjs-throttler` is still available. There is no API change between the packages, just the package name change, so it should be an easy switch  once it is released.
