### ISSUE TITLE
How to send back custom response message when limit reached

### ISSUE THREAD

**Issue by amit-sharma-dev** [nestjs/throttler#353]
On limit reached , i am getting below response.

{
  "status_code": 429,
  "status": false,
  "error": {}
}

I want to add **message** key in above respone body.
Quick response very helpful.

**Comment by jmcdo29** [comment]
Currently, there isn't a way to do this with a custom message. I'll update the class and when this gets published under `@nestjs/throttler` you'll be able to override the `throwError` method to be a custom solution
