### ISSUE TITLE
GQL code example incomplete

### ISSUE THREAD

**Issue by KingNoosh** [nestjs/throttler#405]
```
@Injectable()
export class GqlThrottlerGuard extends ThrottlerGuard {
  getRequestResponse(context: ExecutionContext) {
    const gqlCtx = GqlExecutionContext.create(context);
    const ctx = gql.getContext();
    return { req, ctx.req, res: ctx.res }; // ctx.request and ctx.reply for fastify
  }
}
```

Where is the request pulled from? Where does gqlCtx get used? What is the gql variable as it's undefined anyways.

The code example is quite literally useless, the docs may as well point to documentation about getRequestResponse.

**Comment by jmcdo29** [comment]
Apologies, the [nest docs](https://docs.nestjs.com/security/rate-limiting#graphql) got updated, but I missed updating the README for this. I'll get that fixed shortly

**Comment by KingNoosh** [comment]
Cheers, I'll leave this ticket for you to close.
