### ISSUE TITLE
Property 'storageService' is private and only accessible within class 'ThrottlerGuard'.

### ISSUE THREAD

**Issue by bhushankumar-developer** [nestjs/throttler#411]
I have extended ThrottlerGuard as per the example given in README(https://github.com/nestjs/throttler#working-with-websockets) and in nestjs documentation(https://docs.nestjs.com/security/rate-limiting#websockets), but I'm not able to access the `storageService` as currently it's private member(https://github.com/nestjs/throttler/blob/master/src/throttler.guard.ts#L23), Which is why I'm facing below error : 

```
src/shared/throttle.guard.ts:10:33 - error TS2341: Property 'storageService' is private and only accessible within class 'ThrottlerGuard'.

const ttls = await this.storageService.getRecord(key);
                                   ~~~~~~~~~~~~~~
```

`storageService` should be as `protected`.

**Comment by jmcdo29** [comment]
Good catch. I've got a few other things I need to change, so expect an update soon
