### ISSUE TITLE
serious bug: remaining times is stuck when use "storage" option with nestjs-redis

### ISSUE THREAD

**Issue by DevAngsy** [nestjs/throttler#416]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

```js
export const Throttler: DynamicModule = ThrottlerModule.forRootAsync({
  imports: [Redis],
  inject: [RedisService],
  useFactory(redisService: RedisService): ThrottlerModuleOptions {
    const redisClient = redisService.getClient(REDIS_CLIENT_NAME_THROTTLER);

    return {
      ttl: ms('1m') / 1000,
      limit: 30,
      storage: new ThrottlerStorageRedisService(redisClient),
    };
  },
});
```
- same https://github.com/kkoomen/nestjs-throttler-storage-redis/issues/322
- The X-RateLimit-Remaining in headers of response is stuck when send request about 11-12 times.
- But if not use "storage" option, it works normally.
- I created a mini repo below for this issue.

## Expected behavior

The throttler should works normally.

## Minimal reproduction of the problem with instructions

1. download from https://github.com/DevAngsy/throttle-bug
2. npm install
3. edit redis password according to your redis config
4. npm run start:dev
5. send get request to http://127.0.0.1:3000/app/hello 10-20 times, and notice X-RateLimit-Remaining
6. single-line annotate "storage" option, notice X-RateLimit-Remaining again

## Environment

```
OS Version: Ubuntu 20.04.2 LTS
CPU: Intel® Core™ i5-9600K
NodeJS Version: 14.16.0
NPM Version: 7.6.3
Ubuntu Redis Version: V6
Global Nest CLI Version: 7.5.6
Repo Nest CLI Version: 7.5.6
Repo nestjs-throttler Version: 0.3.0
Repo nestjs-throttler-storage-redis Version: 0.1.11
Repo ioredis Version: 4.24.3
```

**Comment by jmcdo29** [comment]
Without using the RedisStorage, the module throws an exception after 30 requests, as you've set. 

I used this zsh script to test it
```shell
throttlerTest() {
  dummy=count
  count=0
  while true
  do
    curl -s --fail http://localhost:3000/app/hello
    if [ $? -ne 0 ]
    then
      echo "We got rate limited"
      curl -v http://localhost:3000/app/hello
      break
    fi
    (($dummy += 1))
  done
  echo "Requests made before limiting:"
  echo $count
}
```
And got back
```
❯ throttlerTest
Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!We got rate limited
*   Trying ::1:3000...
* TCP_NODELAY set
* Connected to localhost (::1) port 3000 (#0)
> GET /app/hello HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 429 Too Many Requests
< X-Powered-By: Express
< Retry-After: 60
< Content-Type: application/json; charset=utf-8
< Content-Length: 68
< ETag: W/"44-McWaoNlzt3iglN2odEGCDEADErE"
< Date: Wed, 24 Mar 2021 04:05:14 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
{"statusCode":429,"message":"ThrottlerException: Too Many Requests"}Requests made before limiting:
30
```

So like you said, it works normally, meaning there's a problem with how the sub-library works and returns the `ttls` that are used [in this line](https://github.com/nestjs/throttler/blob/master/src/throttler.guard.ts#L82) for the header calculation

**Comment by DevAngsy** [comment]
same issue whit @nestjs/throttler

**Comment by kkoomen** [comment]
Fixed in [kkoomen/nestjs-throttler-storage-redis](https://github.com/kkoomen/nestjs-throttler-storage-redis) v0.1.12.
