### ISSUE TITLE
looks like the module throttles only 20x responses

### ISSUE THREAD

**Issue by flamewow** [nestjs/throttler#522]
looks like the module throttles only 20x responses, if response is 401 
for example if credentials are invalid - module doesn't work.

I wanted to use module to limit number of sign-in attempts to 5 per 60s to eliminate bruteforce attack

**Comment by jmcdo29** [comment]
This module is a guard, so the order of execution would be very important. If your auth guard runs before the throttler guard, then the throttler guard will have no idea about the request

**Comment by flamewow** [comment]
@jmcdo29 thanks for the clarification, haven't thought about the execution order.
You are right.


  @UseGuards(ThrottlerGuard, LocalAuthGuard) - works fine
  
  @UseGuards(LocalAuthGuard, ThrottlerGuard) - doesn't work
