### ISSUE TITLE
Proposal: Add `onLimit` option 

### ISSUE THREAD

**Issue by friebetill** [nestjs/throttler#531]
Are there considerations to add an `onLimit` option, e.g. like in this project [GraphQL Rate Limit](https://github.com/ravangen/graphql-rate-limit#onlimit)?

This would be useful so that one could, throw a `GraphQLError` directly with all the needed formatting (`message`, `extension`, ...).

Currently one can either:
1. have extra logic for the `ThrottlerException` in the `formatError` method or
2. override the `handleRequest` method to throw one's own exception.

Both are imho inelegant workarounds, but on the other side the feature is not a high priority. Probably there are other solutions, but these are the solutions I came up with.

**Comment by jmcdo29** [comment]
What about adding in a new method for `throwError` that passes in the `ExecutionContext`, allowing for easy overriding?

Personally, I'd rather not pass methods through config if we can help it, as extending classes feels more natural in a class-based architecture.

**Comment by friebetill** [comment]
You are right, a protected method `throwError` or maybe better `throwException` sounds more suitable.

**Comment by jmcdo29** [comment]
Would you like to make a PR to add this?

**Comment by friebetill** [comment]
Yes I can try it!
