### ISSUE TITLE
Error: Cannot read property 'ip' of undefined

### ISSUE THREAD

**Issue by webafra** [nestjs/throttler#574]
hello.

I created a new project today and by installing throttler package, I got the following error:

<img width="789" alt="Screen Shot 2021-07-14 at 1 30 03 AM" src="https://user-images.githubusercontent.com/8689072/125524356-3a8b6daa-b410-4f19-901c-7c30fe8bd65d.png">

ENV And Dependency: 
Mac Os Big sur: 11.4
node : 14

"@nestjs/core": "^8.0.0",
"@nestjs/graphql": "^8.0.2",
"@nestjs/platform-express": "^8.0.0",
"@nestjs/throttler": "^2.0.0",
"apollo-server-express": "^2.25.2",

**Comment by jmcdo29** [comment]
Did you [customize the `ThrottlerGuard`](https://docs.nestjs.com/security/rate-limiting#graphql) to wor with GraphQL?

**Comment by jmcdo29** [comment]
Looks like this is all good? Let me know if not and provide a minimum reproduction.

**Comment by webafra** [comment]
thanks @jmcdo29 , this work for me 💯
