### ISSUE TITLE
make error message configurable

### ISSUE THREAD

**Issue by TrejGun** [nestjs/throttler#621]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to override the default error message

for now, I have to override ThrottleGuard like this

```ts
class MyThrottlerGuard extends ThrottlerGuard {
  protected throwThrottlingException(): void {
    throw new ThrottlerException("My Error Message");
  }
}
```

### Describe the solution you'd like

I would like to pass the error message to the module config function
```ts
    ThrottlerModule.forRoot({
      ttl: 3600,
      limit: 100,
      throttlerMessage: "My Error Message"
    }),
```

### What is the motivation / use case for changing the behavior?

I need to localize error messages in my app

**Comment by jmcdo29** [comment]
What's wrong with the extending approach? How would making a new option change what needs to be done?

**Comment by TrejGun** [comment]
It is shorter)))
And it looks like it was supposed to be parametrized but for some reason, it is not

**Comment by jmcdo29** [comment]
Well, the extendable configuration was originally created for to #353 and #357. I find it cleaner to deal with extending the class rather than passing in a value via the module configuration.

**Comment by TrejGun** [comment]
at least it works
