### ISSUE TITLE
Lock the route for user ip and not in general

### ISSUE THREAD

**Issue by AndonMitev** [nestjs/throttler#779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello guys i used to provided code in the example:

```
import { APP_GUARD } from '@nestjs/core';
import { ThrottlerGuard, ThrottlerModule } from '@nestjs/throttler';

@Module({
  imports: [
    ThrottlerModule.forRoot({
      ttl: 60,
      limit: 10,
    }),
  ],
  providers: [
    {
      provide: APP_GUARD,
      useClass: ThrottlerGuard,
    },
  ],
})
export class AppModule {}
```

Which says: `The above would mean that 10 requests from the same IP can be made to a single endpoint in 1 minute.`

But when i make 10 requests from one IP then i'm not able to access from different IP it says 429 for both different IP's, any idea if there are some additional settings that should be make or something

### Minimum reproduction code

The above would mean that 10 requests from the same IP can be made to a single endpoint in 1 minute.

### Expected behavior

When 1 ip reach the limit, endpoint to be open for different ip's

### Package version

^2.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
How are you checking the different IPs? Do you have an easy way to reproduce this in a minimum reproduction?

**Comment by micalevisk** [comment]
I've managed to reproduce this with 2 IPs using the following config:

```
ThrottlerModule.forRoot({
  ttl: 60,
  limit: 3,
})
```

Using https://repl.it and my machine to simulate two different IPs, and [ngrok](https://ngrok.com) (free plan) to make the local server public available

https://user-images.githubusercontent.com/13461315/150908521-44130d47-4251-4494-990f-7ec2ba6dc585.mp4

Here's the repo with instructions: https://gitlab.com/micalevisk/nestjs-throttler-issues-779

**Comment by jmcdo29** [comment]
@micalevisk when using ngrok and repl.it does the IP assignned to `repl.it` end up being the `localhost` IP (127.0.0.1) after some forwarding, or does it keep the repl.it IP?

**Comment by micalevisk** [comment]
@jmcdo29 On the repo, I've added a middleware that prints `req.ip` 

![image](https://user-images.githubusercontent.com/13461315/151097600-41b1fd23-ad41-4605-b732-50f50d798a48.png)

I _believe_ this is enough to proof that they aren't the same.

**Comment by jmcdo29** [comment]
Very interesting

**Comment by micalevisk** [comment]
sorry, I've mislead you @jmcdo29 (and myself).

In the demo I didn't add the `app.set('trust proxy', true)` as the docs advised [here](https://docs.nestjs.com/security/rate-limiting#proxies)

I just test my repo again and it **doesn't** reproduce the issue. Thus @AndonMitev you must provide some repo if you still belive that this issue exists.

**Comment by jmcdo29** [comment]
I'm going to close this, as I haven't seen a reproduction for it. If you provide us a way to reproduce the error, I can take a look again.
